services:
  mysql:
    container_name: dummydata-generator_mysql
    image: mysql:8
    ports:
      - '3300:3306'
    environment:
      TZ: 'Asia/Seoul'
      MYSQL_DATABASE: dummydata-generator
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./infra/mysql/data:/var/lib/mysql
    networks:
      - dummydata-generator
networks:
  dummydata-generator:
    name: dummydata-generator
    driver: bridge
